name: Continuous Integration - Node 16

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  BuildingAndTesting:
    name: Building and Testing with node v16
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Prepare project for Node 16
        run: |
          rm -rf .yarn yarn.lock .yarnrc.yml
          jq 'del(.packageManager)' package.json > package.json.tmp
          mv package.json.tmp package.json
      - name: Use Node.js v16
        uses: actions/setup-node@v4
        with:
          node-version: v16
      - name: Install Dependencies
        run: yarn install --ignore-engines
      - name: Typecheck And Build Code
        run: yarn typecheck && yarn build
      - name: Run tests
        run: yarn test
