name: Continuous Integration - Node 16

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  BuildingAndTesting:
    name: Building and Testing with node v16
    runs-on: ubuntu-latest
    env:
      YARN_IGNORE_ENGINES: true
      YARN_IGNORE_NODE: 1
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Prepare project for Node 16
        run: |
          rm -rf .yarn yarn.lock .yarnrc.yml
          jq 'del(.packageManager)' package.json > package.json.tmp
          mv package.json.tmp package.json
      - name: Install dependencies
        uses: sapphiredev/.github/actions/install-yarn-dependencies@main
        with:
          node-version: 16
      - name: Typecheck And Build Code
        run: yarn typecheck && yarn build
      - name: Run tests
        run: yarn test
